name: Release

on:
  push:
    tags: [ "*" ]

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: taiki-e/create-gh-release-action@v1
        with:
          changelog: CHANGELOG.md
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  update-release:
    name: Publish binaries
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build
        run: |
          yarn 
          yarn build
      - uses: montudor/action-zip@v1
        with:
          args: zip -j -r avatar-wallet.zip build/ LICENSE
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: avatar-wallet.zip
          tag: ${{ github.ref }}
          overwrite: true
